FROM nginxinc/nginx-unprivileged:1.27-alpine AS runtime

COPY --chown=101:101 dist /usr/share/nginx/html
COPY --chown=101:101 docker/env.js.template /usr/share/nginx/html/env.js.template
COPY --chown=101:101 configuracoes/default.conf /etc/nginx/conf.d/default.conf
COPY --chown=101:101 startup.sh /startup.sh

USER root
RUN chmod 755 /startup.sh

USER 101:101

EXPOSE 8080

ENTRYPOINT ["/startup.sh"]
