FROM nginxinc/nginx-unprivileged:1.27-alpine AS runtime

COPY dist /usr/share/nginx/html
COPY docker/env.js.template /usr/share/nginx/html/env.js.template
COPY configuracoes/default.conf /etc/nginx/conf.d/default.conf
COPY --chmod=555 startup.sh /startup.sh

USER 101:101

EXPOSE 8080

ENTRYPOINT ["/startup.sh"]
